### ISSUE TITLE
爬取用户听歌排行信息不可用

### ISSUE THREAD

**Issue by taoey** [wenhaoliang/netease-music-spider#2]
可以拿“34364835”这个歌曲id尝试一下（评论用户比较少）

**Comment by wenhaoliang** [comment]
这个需要更新一下params和encSecKey，具体方法是随便打开一个用户的听歌排行，用F12观察到发送出去的params和encSecKey，替换掉我的代码里面params和encSecKey。
下面我更新了一下，你可以直接拿去用。

> params:

`aSYSRQ/Ym4gi0igKo1AbwEFE5P5jMPwkPjR4CNBCPYmHHU4FVkwbTfJq/CzafPrf86wBk4hqC7cbn28QPOwkoWT4BvOMuct9+R3qF39ZQEXyFaqeMBOpGbPW2bCRyBlrvDTcqTthfqYUnhj2/rFhYA2QEXieqhBHl8CratK9yOTtuSgxQSGumnseTYJC2Lrc`

> encSecKey

`d56372e0bde8c51991d343934dc015dd845a363392af284e5cd6f34ee4526b0f4a4eb3ca27f8bec6b7ff896f7520620078b0cefa37b9edaf63d642ac61112ac74ed7f6575cbb1944ef098808e985e9a16b8396a29205d10e0dbdd0b8f76130e65495c32df111f06541f888f31849e4f234892e6d7a9c444d67a3001ebafc8d31`

**Comment by yangyangyang1995** [comment]
你用的是哪个python版本？为什么我在try的end结尾处都一直在报错呀

**Comment by import-yuefeng** [comment]
没看错的话是基于python3的, 你报错的原因可能是因为他的两个加密参数失效, 或者数据库没按要求打开 引起的, 具体问题你需要贴一下异常栈.
